version: '3.8'

services:
  frontend:
    build: ../spanda-frontend
    ports:
      - "3000:3000"
    networks:
      - spanda-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - spanda-network
    volumes:
      - mongo_data:/data/db

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    networks:
      - spanda-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - spanda-network

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    networks:
      - spanda-network

  bytewax:
    build: ./goldenverba/streaming
    networks:
      - spanda-network

  mlflow:
    image: mlflow/mlflow:latest
    ports:
      - "5000:5000"
    networks:
      - spanda-network

  training:
    build: ./goldenverba/training
    networks:
      - spanda-network

  inference:
    build: ./goldenverba/inference
    ports:
      - "8001:8001"
    networks:
      - spanda-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - spanda-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3001"
    networks:
      - spanda-network

networks:
  spanda-network:

volumes:
  mongo_data:
  weaviate_data:
  grafana_data:
  mlflow_data:
